apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-coll-05d38d255a1842c2aa5fba3614db71e9-depl
  labels:
    app: users-coll-05d38d255a1842c2aa5fba3614db71e9
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-coll-05d38d255a1842c2aa5fba3614db71e9
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: users-coll-05d38d255a1842c2aa5fba3614db71e9
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: users-coll-05d38d255a1842c2aa5fba3614db71e9
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:users-coll-05d38d255a1842c2aa5fba3614db71e9
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping